server:
  port: 8060

spring:
  application:
    name: api-gateway
  #  config:
  #    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: limits-service
          uri: lb://limits-service
          predicates:
            - Path=/limits-service/**

        - id: currency-exchange-service
          uri: lb://currency-exchange-service
          predicates:
            - Path=/currency-exchange/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/